"""
File: Cont_Bill.py
Name: Adrian Carreno, Ali Maamoun
Date: 04/23/24
Description: Controller Bill related taks
Purposes: Controller Class for Property Page to handle the bills for a property.
Adds new bills, searches for bills, and more.
"""

from System import Bill, db


# NEED DATABASE FUNCTIONS

class Cont_Bill:
    """Controller for actions regarding Bills which need database access
    """
    def __init__(self, acc_id, prop_id):
        """Initializes a controller for bills

        Args:
            acc_id (_type_): The account associated with this controller
            prop_id (_type_): The property database ID associated with this controller
        """
        self.account_id = acc_id
        self.property_id = prop_id
        self.bills : dict[int,Bill] #dictionary of bills for one property
        if prop_id is not None:
            self.update_bills(prop_id)

    def create_bill(self, description : str, type : str, amount : int):
        """Creates a bill into the database and locally

        Args:
            description (str): Bill's name
            type (str): pay or collect
            amount (int): dollar amount

        Returns:
            _type_: bill_id generated by db
        """
        new_bill = Bill(account_id=self.account_id, property_ID=self.property_id, description= description, amount = amount, bill_type=type)
        print(f"billtype in here: {new_bill.get_type()}")
        bill_id = db.addToBill(self.property_id, new_bill)
        self.add_bill(new_bill.get_bill_id(), new_bill)
        return bill_id

    def add_bill(self, bill_id, bill):
        """adds the new bill locally to the dictionary

        Args:
            bill_id (_type_): database ID
            bill (_type_): bill object
        """
        self.bills.update({bill_id : bill})

    def remove_bill(self, bill_id):
        """Removes a bill from the dictionary by its ID

        Args:
            bill_id (_type_): ID to remove

        Returns:
            _type_: Returns the popped bill
        """
        return self.bills.pop(bill_id)
    
    def delete_bill(self, bill_id):
        """Removes bill from database table

        Args:
            bill_id (int): database ID to remove
        """
        db.deleteBill(bill_id)
        self.remove_bill(bill_id)

    def get_bills(self) -> dict[int,Bill]:
        """reads the database to get new changes

        Returns:
            dict[int,Bill]: updates its local records
        """
        self.update_bills()
        return self.bills
    
    def change_property(self, prop_id):
        """changes the scope of which property controller is looking at.
        """
        #set new property ID
        self.property_id = prop_id
        #update bills
        self.update_bills()

    def update_bills(self):
        """reads the database and updates records
        """
        self.bills = db.readBills(self.property_id)

    def find_bill_id(self, description, amount):
        """searches for database ID through the dictionary
        searches for matching description and price

        Args:
            description (_type_): name of bill to find 
            amount (_type_): price of bill to match

        Returns:
            _type_: database ID
        """
        for bill_instance in self.bills.values():
            if bill_instance.getDescription() == description and bill_instance.getAmount() == amount:
                return bill_instance.billID()